services:
  - type: web
    name: python-script-bot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      pip install waitress
    startCommand: |
      waitress-serve --port=$PORT app:app
    envVars:
      - key: PORT
        value: 5000
      - key: TELEGRAM_TOKEN
        value: 7953276961:AAFMas8PAjUVapJzVXurDEg5ACwoGfkW-_s
      - key: ADMINS
        value: "8167507955"
