services:
  - type: web
    name: python-script-bot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: TELEGRAM_TOKEN
        value: "7953276961:AAFMas8PAjUVapJzVXurDEg5ACwoGfkW-_s"
      - key: ADMINS
        value: "8167507955"
      - key: PORT
        value: 5000
    plan: free
