services:
  - type: web
    name: python-script-bot
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app
    envVars:
      - key: PORT
        value: 5000
      - key: TELEGRAM_TOKEN
        value: "7953276961:AAFMas8PAjUVapJzVXurDEg5ACwoGfkW-_s"
      - key: ADMINS
        value: "8167507955"
    plan: free
